version: "3.3"

services:
  postgres:
    image: postgres:15.1
    container_name: hawapi-postgres
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hawapi
    ports:
      - "5432:5432"