name: "Build, Publish and Release"

on:
  push:
    tags:
      - 'v*'

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build-publish-and-release:
    runs-on: ubuntu-latest
    steps:
      # Setup

      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup yarn (Node 18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # Build

      ## Build website, docs, javadoc and the project (Without tests)
      - name: Build project
        run: make build-wot

      ## Push to GHCR (GitHub Container Registry)
      - name: Docker build
        run: docker build --rm=false -t ghcr.io/${{ github.action_repository }}:${{ github.ref_name }} .

      # Publish

      - name: GitHub (GHCR) login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u LucJosin --password-stdin

      - name: GitHub (GHCR) push
        run: docker push ghcr.io/${{ github.action_repository }}:${{ github.ref_name }}

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      # Release

      - name: Deploy to Koyeb
        run: koyeb service redeploy hawapi/hawapi