# Workflow ref: https://github.com/wesleyegberto/gh-actions-java/blob/master/.github/workflows/build-test-deploy.yml
# Docker ref: https://dev.to/saulsilver/docker-stop-all-processes-on-github-actions-533j
name: "Java Unit/Integration testing"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    # Ignore drafts
    if: github.event.pull_request.draft == false
    name: Java Unit/Integration testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'

      - name: Maven Test
        run: mvn test

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
